name: Diff Generated Files

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: old
          ref: ${{ github.base_ref }}

      - uses: actions/checkout@v2
        with:
          path: new
#          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        
      - name: Install JSonnet
        run: |
          go get github.com/google/go-jsonnet/cmd/jsonnet
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build old repository
        working-directory: old/
        run: |
          scripts/gen-tests.sh
   
      - name: Build new repository
        working-directory: new/
        run: |
          scripts/gen-tests.sh

      - name: Diff old and new
        run: |
          diff -rN old/k8s new/k8s || true
