name: Diff Generated Files

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#        with:
#          path: old
#          ref: ${{ github.base_ref }}

      - uses: actions/checkout@v2
        with:
          path: new
#          ref: ${{ github.head_ref }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          apt-get update
          apt-get update -y jsonnet
          new/scripts/gen-tests.sh 
