name: Diff Generated Files

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, edited]
  
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        
      - name: Install JSonnet
        run: |
          go get github.com/google/go-jsonnet/cmd/jsonnet
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build repository
        run: |
          scripts/gen-tests.sh

      - name: Show git diff
        run: |
          git diff --color origin/gen -- k8s/ | tee generated.diff
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: diff
          path: generated.diff
